#!/bin/bash

volume_name_nginx_web_content=$1

volume_web_content_pathname=$(/bin/bash get-docker-volume-pathname "${volume_name_nginx_web_content}")
volume_tools_pathname=$volume_web_content_pathname/tools/
echo "[DEBUG] Init clone tools in $volume_tools_pathname"
cd $volume_tools_pathname

manage_tool() {
  tool=$1
  echo "[DEBUG] Init tool ${tool}"
  rm -rf ${tool}
  git clone --depth=1 --branch=main https://github.com/CarlosAMolina/${tool}
  rm -rf ${tool}/.git
}

github_names=("open-urls" "job-check-lambda-name" "job-modify-issue-name")
for name in ${github_names[@]};
do
  manage_tool ${name}
done
