#!/bin/bash

volume_name_nginx_web_content=$1
volume_name_pandoc=$2

# Pandoc
volume_pandoc_pathname=$(/bin/bash get-docker-volume-pathname ${volume_name_pandoc})
echo "[ÐEBUG] Init copy web content to $volume_pandoc_pathname"
cd md-to-html
cp -r pandoc-config $volume_pandoc_pathname
cp -r create-pandoc-script-for-files $volume_pandoc_pathname
cp convert-md-to-html $volume_pandoc_pathname
cp run-create-pandoc-script-for-files $volume_pandoc_pathname
cd -

# Web content
volume_web_content_pathname=$(/bin/bash get-docker-volume-pathname "${volume_name_nginx_web_content}")
echo "[ÐEBUG] Init copy web content to $volume_web_content_pathname"
cp -r ../src/* $volume_web_content_pathname
