# syntax=docker/dockerfile:1
ARG docker_image
FROM $docker_image
# No forward logs to Docker log collector.
RUN unlink /var/log/nginx/access.log
RUN unlink /var/log/nginx/error.log
# Config
COPY nginx/nginx.conf /etc/nginx/
COPY nginx/default.conf /etc/nginx/conf.d/
