#!/bin/bash

# Although the docker daemon is active, on some systems it takes some time before docker runs.

docker ps &> /dev/null
exit_status=$?
if test "$exit_status" == "0"; then
  echo 0 # 0 = true
else
  echo 1 # 1 = false
fi
