#!/bin/bash

container=$1

stop_if_running() {
  container=$1
  echo "[DEBUG] Init stop container ${container}"

  if [ $(/bin/bash is-container-running ${container}) -eq 0 ]; then
    echo "[DEBUG] The container is running. Init stop"
    docker stop ${container} || true
    if [ $(/bin/bash is-container-running ${container}) -eq 0 ]; then
      echo "[ERROR] The container has not been stopped"
      exit 1
    else
      echo "[DEBUG] The container has been stopped"
    fi
  else
    echo "[DEBUG] The container is not running, no action is required"
  fi
}

stop_if_running ${container}

