#!/bin/bash

# https://stackoverflow.com/questions/3258243/check-if-pull-needed-in-git
# https://stackoverflow.com/questions/21703653/git-pull-check-if-a-file-changed-bash

filename="makefile"
echo "[DEBUG] Init check if the $filename file is updated"
file_hash_old=$(git rev-parse HEAD:./$filename)
/bin/bash update-git-current-branch
file_hash_new=$(git rev-parse HEAD:./$filename)
if [ $file_hash_old == $file_hash_new ]; then
  echo "[DEBUG] The $filename file is updated"
else
  # If the main makefile file was updated in origin,
  # its last version won't be used despite pulling it
  # because the old version is running.
  echo "[ERROR] The required file $filename didn't have all the remote changes. Remote changes have been downloaded. Please deploy again"
  exit 1
fi

