#!/bin/bash

set -e # Exit if any command fails.

main_project_pathname=$1

projects_pathname=$main_project_pathname/src/projects
echo "[DEBUG] Init clone projects"

PROJECT_FOLDER_NAME=check-iframe
echo "[DEBUG] Init project ${PROJECT_FOLDER_NAME}"
project_pathname=$projects_pathname/$PROJECT_FOLDER_NAME
if [ -d "$project_pathname" ]; then
    echo "[DEBUG] Deleting old project content pathname ${project_pathname}"
    rm -rf $project_pathname
fi
echo "[DEBUG] Cloning project ${PROJECT_FOLDER_NAME}"
git clone --depth=1 --branch=main https://github.com/CarlosAMolina/checkIframe /tmp/${PROJECT_FOLDER_NAME}
mkdir $project_pathname
echo "[DEBUG] Moving cloned docs files to the current repository"
mv /tmp/${PROJECT_FOLDER_NAME}/docs/* ${project_pathname}
echo "[DEBUG] Deleting cloned project repository"
rm -rf /tmp/${PROJECT_FOLDER_NAME}
